version: "3.1"

services:
  ticket-test:
    image: denvazh/gatling:latest
    external_links:
      - ticketservice
    networks:
      - ticket-net
    volumes:
      - ./ticket-service-gatling/conf:/opt/gatling/conf
      - ./ticket-service-gatling/user-files:/opt/gatling/user-files
      - ./ticket-service-gatling/results:/opt/gatling/results

networks:
  ticket-net:
    driver: bridge
