version: "3.1"

services:
  ticket-test:
    image: denvazh/gatling:latest
    external_links:
      - ticketreservation
    networks:
      - ticket-net
    environment:
      - JAVA_OPTS=${JAVA_OPTS_TEST}
    volumes:
      - ./ticket-reservation-gatling/conf:/opt/gatling/conf
      - ./ticket-reservation-gatling/user-files:/opt/gatling/user-files
      - ./ticket-reservation-gatling/results:/opt/gatling/results

networks:
  ticket-net:
    driver: bridge
