version: "3.1"

services:
  ticket:
    image: andreformento/realtimeticket-ticketservice:latest
    container_name: ticketservice
    networks:
      - ticket-net
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - data-mongo:/data/db
    networks:
      - ticket-net

volumes:
  data-mongo:

networks:
  ticket-net:
    driver: bridge
