version: "3.1"

services:
  ticket:
    image: andreformento/realtimeticket-ticketreservation:latest
    container_name: ticketreservation
    networks:
      - ticket-net
    ports:
      - 8080:8080
    links:
      - redisdb
    environment:
      SPRING_REDIS_HOSTNAME: redisdb
      SPRING_REDIS_PORT: 6379
  redisdb:
    image: redis:alpine
    hostname: redisdb
    networks:
      - ticket-net

volumes:
  data-redis:

networks:
  ticket-net:
    driver: bridge
